In [1]:
import numpy as np

import pandas as pd

df=pd.read_csv("C:\\Users\\rajen\\OneDrive\\Desktop\\data\\HeavyRain.csv")

df.head()

Unnamed: 0        date  month  day  previous_rainfall   rainfall
0           0  2022-01-01      1    1          54.881350  50.106317
1           1  2022-01-02      1    2          71.518937  37.638916
2           2  2022-01-03      1    3          60.276338  36.491184
3           3  2022-01-04      1    4          54.488318  26.090450
4           4  2022-01-05      1    5          42.365480  49.597030

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
mn=MinMaxScaler()

In [3]:
df[["month","day","previous_rainfall","rainfall"]]=mn.fit_transform(df[["month","day","previous_rainfall","rainfall"]])

df.head()

Unnamed: 0        date  month       day  previous_rainfall  rainfall
0           0  2022-01-01    0.0  0.000000           0.547987  0.500887
1           1  2022-01-02    0.0  0.033333           0.714935  0.376121
2           2  2022-01-03    0.0  0.066667           0.602123  0.364635
3           3  2022-01-04    0.0  0.100000           0.544043  0.260551
4           4  2022-01-05    0.0  0.133333           0.422398  0.495790

In [4]:
df=df.drop(columns=["Unnamed: 0","date"])

In [5]:
x=df[["month","day","previous_rainfall"]].values
print(x.ndim)
x

2


array([[0.        , 0.        , 0.54798727],
       [0.        , 0.03333333, 0.71493496],
       [0.        , 0.06666667, 0.60212256],
       ...,
       [1.        , 0.93333333, 0.98802976],
       [1.        , 0.96666667, 0.75917959],
       [1.        , 1.        , 0.36308506]])

In [6]:
y=df["rainfall"].values
print(y.ndim)
y

1


array([5.00886555e-01, 3.76120537e-01, 3.64634748e-01, 2.60550661e-01,
       4.95789919e-01, 6.81696654e-01, 2.76998561e-01, 5.24220399e-01,
       1.16920545e-01, 1.59416874e-01, 4.62945268e-02, 9.70901408e-01,
       3.31683240e-03, 1.78165380e-01, 6.12772639e-01, 8.08832762e-02,
       8.82000914e-01, 7.19604820e-01, 9.66556733e-01, 5.07463779e-01,
       3.00078993e-01, 5.49359698e-01, 9.30959229e-01, 5.20599355e-01,
       2.66857844e-01, 8.77499881e-01, 3.71646831e-01, 8.38003034e-04,
       2.47321429e-01, 3.17921976e-01, 8.58864819e-01, 4.58295143e-01,
       4.44368995e-01, 3.35803919e-01, 8.80781635e-01, 9.45177774e-01,
       9.92075908e-01, 3.76472908e-01, 9.66314028e-01, 7.91917554e-01,
       6.75641392e-01, 2.44523823e-01, 2.16070624e-01, 1.65623989e-01,
       9.22891173e-01, 2.93747303e-01, 4.52882230e-01, 4.93775973e-01,
       7.78199465e-01, 8.44311581e-01, 1.38628959e-01, 4.26673018e-01,
       8.42930489e-01, 8.18090590e-01, 1.01942965e-01, 1.55952381e-01,
      

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
x

array([[0.        , 0.        , 0.54798727],
       [0.        , 0.03333333, 0.71493496],
       [0.        , 0.06666667, 0.60212256],
       ...,
       [1.        , 0.93333333, 0.98802976],
       [1.        , 0.96666667, 0.75917959],
       [1.        , 1.        , 0.36308506]])

In [9]:
y

array([5.00886555e-01, 3.76120537e-01, 3.64634748e-01, 2.60550661e-01,
       4.95789919e-01, 6.81696654e-01, 2.76998561e-01, 5.24220399e-01,
       1.16920545e-01, 1.59416874e-01, 4.62945268e-02, 9.70901408e-01,
       3.31683240e-03, 1.78165380e-01, 6.12772639e-01, 8.08832762e-02,
       8.82000914e-01, 7.19604820e-01, 9.66556733e-01, 5.07463779e-01,
       3.00078993e-01, 5.49359698e-01, 9.30959229e-01, 5.20599355e-01,
       2.66857844e-01, 8.77499881e-01, 3.71646831e-01, 8.38003034e-04,
       2.47321429e-01, 3.17921976e-01, 8.58864819e-01, 4.58295143e-01,
       4.44368995e-01, 3.35803919e-01, 8.80781635e-01, 9.45177774e-01,
       9.92075908e-01, 3.76472908e-01, 9.66314028e-01, 7.91917554e-01,
       6.75641392e-01, 2.44523823e-01, 2.16070624e-01, 1.65623989e-01,
       9.22891173e-01, 2.93747303e-01, 4.52882230e-01, 4.93775973e-01,
       7.78199465e-01, 8.44311581e-01, 1.38628959e-01, 4.26673018e-01,
       8.42930489e-01, 8.18090590e-01, 1.01942965e-01, 1.55952381e-01,
      

In [10]:
import tensorflow as tf

In [11]:
from tensorflow import keras

In [12]:
from keras.models import Sequential

In [13]:
from keras.layers import Dense

In [17]:
model=Sequential()
model.add(Dense(64,activation="relu",input_shape=(x_train.shape[1],)))
model.add(Dense(32,activation="relu"))
model.add(Dense(1,activation="linear"))

In [20]:
model.compile(optimizer="adam",loss="mean_squared_error",metrics=["accuracy"])

In [21]:
model.fit(x_train,y_train,epochs=10,batch_size=10,verbose=1)

Epoch 1/10
59/59 [==============================] - 1s 3ms/step - loss: 0.0890 - accuracy: 0.0017
Epoch 2/10
59/59 [==============================] - 0s 5ms/step - loss: 0.0888 - accuracy: 0.0000e+00
Epoch 3/10
59/59 [==============================] - 0s 5ms/step - loss: 0.0877 - accuracy: 0.0000e+00
Epoch 4/10
59/59 [==============================] - 0s 4ms/step - loss: 0.0862 - accuracy: 0.0000e+00
Epoch 5/10
59/59 [==============================] - 0s 4ms/step - loss: 0.0858 - accuracy: 0.0000e+00
Epoch 6/10
59/59 [==============================] - 0s 3ms/step - loss: 0.0860 - accuracy: 0.0000e+00
Epoch 7/10
59/59 [==============================] - 0s 4ms/step - loss: 0.0852 - accuracy: 0.0000e+00
Epoch 8/10
59/59 [==============================] - 0s 5ms/step - loss: 0.0858 - accuracy: 0.0000e+00
Epoch 9/10
59/59 [==============================] - 0s 4ms/step - loss: 0.0855 - accuracy: 0.0000e+00
Epoch 10/10
59/59 [==============================] - 0s 4ms/step - loss: 0.0853 - accu

In [22]:
y_pred=model.predict(x_test)

5/5 [==============================] - 0s 3ms/step


In [25]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,accuracy_score


In [26]:
mean_squared_error(y_test,y_pred)

0.09481955472856465

In [27]:
mean_absolute_error(y_test,y_pred)

0.26569972661063385

In [29]:
accuracy_score(y_test,y_pred,normalize=False)

ValueError: continuous is not supported